### ISSUE TITLE
improve sampler.js

### ISSUE THREAD

**Issue by marian-cojoc-ro** [arminrosu/json-lean#3]
- [x] make the _output_ directory if it does not exist
- [x] clean the _output_ directory on every run
- [x] document the _output_ directory in the readme since it's not tracked

**Comment by arminrosu** [comment]
Hmm, I thought it was pretty self-evident. 

Anything you'd like me to add in sampler.js?

**Comment by marian-cojoc-ro** [comment]
no.. i'll have a PR for this soon enough if that's ok

**Comment by arminrosu** [comment]
That would be great :)
